name: Deploy to VPS

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files via SSH
      run: |
        rsync -avz --delete --chown=www-data:www-data \
          --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
          --exclude='.git' \
          --exclude='.github' \
          --exclude='node_modules' \
          --exclude='vendor' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.PROJECT_PATH }}

    - name: Run post-deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.PROJECT_PATH }} && \
          # Buat folder yang diperlukan
          mkdir -p bootstrap/cache storage/framework/{cache,sessions,views} && \
          # Set permission
          sudo chown -R www-data:www-data bootstrap/cache storage
          sudo chmod -R 775 bootstrap/cache storage && \
          # Install dependencies
          composer install --no-dev --optimize-autoloader && \
          # Setup Laravel
          [ -f .env ] || cp .env.example .env && \
          php artisan key:generate --force && \
          php artisan config:clear && \
          php artisan optimize && \
          php artisan storage:link"