name: Deploy to VPS

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files via SSH
      run: |
        rsync -avz --delete --chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r \
        --exclude='.git' \
        --exclude='.github' \
        --exclude='node_modules' \
        --exclude='vendor' \
        -e "ssh -o StrictHostKeyChecking=no" \
        ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:${{ secrets.PROJECT_PATH}}

    - name: Run post-deploy commands
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          "cd ${{ secrets.PROJECT_PATH }} && \
          export PATH=\$PATH:/usr/local/bin && \
          sudo chown -R ${{ secrets.VPS_USERNAME }}:www-data ${{ secrets.PROJECT_PATH }} && \
          sudo chmod -R 775 ${{ secrets.PROJECT_PATH }}" && \
          # Install dependencies
          npm install --no-audit --no-fund && \
          npm run build && \
          composer install --no-dev --optimize-autoloader && \
          # Laravel setup
          [ -f .env ] || cp .env.example .env && \
          php artisan key:generate && \
          php artisan migrate --force && \
          php artisan optimize && \
          php artisan storage:link"
